---
title: "Churchill Data Averaging and SE"
author: "Dani Trangmoe"
date: "`r Sys.Date()`"
output: html_document
---

```{r, include=FALSE}
rm(list = ls())
Sys.setenv(TZ = "UTC")

library(data.table)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(RColorBrewer)

```


# Load Data

```{r}

df_avg_23_24 <- fread('./bothyears_daily_avg.csv')

```

# Season Averages

### individual seasons
Averages over each season within each year, and includes no. of days in the season
```{r}


df_avg_biomet <- df_avg_23_24 %>%
  group_by(season) %>%
  summarize(
    nee = round(mean(FC, na.rm = TRUE), 3),
    tair = round(mean(TA, na.rm = TRUE), 2),
    tsoil5 = round(mean(TS_2_05_1, na.rm = TRUE), 2),
    swc = round(mean(SWC_1_1_1, na.rm = TRUE), 2),
    ws = round(mean(WS, na.rm = TRUE), 2),
    nee.se = round(std.error(FC, na.rm = TRUE), 2),
    tair.se = round(std.error(TA, na.rm = TRUE), 2),
    tsoil5.se = round(std.error(TS_2_05_1, na.rm = TRUE), 2),
    swc.se = round(std.error(SWC_1_1_1, na.rm = TRUE), 2),
    ws.se = round(std.error(WS, na.rm = TRUE), 2)
    ) %>%
  mutate(
    nee_with_se = paste0(nee, " ± ", nee.se),  # Combine value and SE
    tair_with_se = paste0(tair, " ± ", tair.se),
    tsoil5_with_se = paste0(tsoil5, " ± ", tsoil5.se),
  swc_with_se = paste0(swc, " ± ", swc.se),
  ws_with_se = paste0(ws, " ± ", ws.se)
  )%>%
  select(season, nee_with_se, tair_with_se, tsoil5_with_se, swc_with_se, ws_with_se) %>%
    arrange(factor(season, levels = c("Fall Senescence 2022", "Winter 2022", "Snow Melt 2023", "Growing Season 2023", "Fall Senescence 2023", "Winter 2023", "Snow Melt 2024", "Growing Season 2024", "Fall Senescence 2024")))


season_counts <- 
  df_avg_23_24 %>%
  filter(season %in% c("Fall Senescence 2022", "Winter 2022", 
                       "Snow Melt 2023", "Growing Season 2023", 
                       "Fall Senescence 2023", "Winter 2023", 
                       "Snow Melt 2024", "Growing Season 2024", 
                       "Fall Senescence 2024")) %>%
  count(season) %>%
    arrange(factor(season, levels = c("Fall Senescence 2022", "Winter 2022", "Snow Melt 2023", "Growing Season 2023", "Fall Senescence 2023", "Winter 2023", "Snow Melt 2024", "Growing Season 2024", "Fall Senescence 2024")))


df_avg_biomet <- right_join(df_avg_biomet, season_counts, by = "season") 



```



### both years
Averages data for each season across both years
```{r}


#Averages over each season within each year, and includes no. of days
df_avg_both <- df_avg_23_24 %>%
  group_by(season_name) %>%
  summarize(
    nee = round(mean(FC, na.rm = TRUE), 3),
    ch4 = round(mean(FCH4, na.rm = TRUE), 3),
    tair = round(mean(TA, na.rm = TRUE), 2),
    tsoil5 = round(mean(TS_2_05_1, na.rm = TRUE), 2),
    swc_1 = round(mean(SWC_1_1_1, na.rm = TRUE), 2),
    swc_2 = round(mean(SWC_2_1_1, na.rm = TRUE), 2),
    ws = round(mean(WS, na.rm = TRUE), 2),
    nee.se = round(std.error(FC, na.rm = TRUE), 2),
    ch4.se = round(std.error(FCH4, na.rm = TRUE), 2),
    tair.se = round(std.error(TA, na.rm = TRUE), 2),
    tsoil5.se = round(std.error(TS_2_05_1, na.rm = TRUE), 2),
    swc_1.se = round(std.error(SWC_1_1_1, na.rm = TRUE), 2),
    swc_2.se = round(std.error(SWC_2_1_1, na.rm = TRUE), 2),
    ws.se = round(std.error(WS, na.rm = TRUE), 2)
    ) %>%
  mutate(
    nee_with_se = paste0(nee, " ± ", nee.se),  # Combine value and SE
    ch4_with_se = paste0(ch4, " ± ", ch4.se),
    tair_with_se = paste0(tair, " ± ", tair.se),
    tsoil5_with_se = paste0(tsoil5, " ± ", tsoil5.se),
  swc_1_with_se = paste0(swc_1, " ± ", swc_1.se),
  swc_2_with_se = paste0(swc_2, " ± ", swc_2.se),
  ws_with_se = paste0(ws, " ± ", ws.se)
  )%>%
  select(season_name, nee_with_se, ch4_with_se, tair_with_se, tsoil5_with_se, swc_1_with_se,swc_2_with_se, ws_with_se) %>%
    arrange(factor(season_name, levels = c("Fall Senescence", "Winter", "Snow Melt", "Growing Season")))


```

