---
title: "Soil Temp Heat Map"
author: "Dani Trangmoe"
date: "`r Sys.Date()`"
output: html_document
---

```{r, include=FALSE}
rm(list = ls())
Sys.setenv(TZ = "UTC")

library(data.table)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(RColorBrewer)

```

# Load data

```{r}

df_23_24 = fread('./bothyears_HH.csv')

```



## Create dataframe

```{r}

# Create new data frame for plot; one column is timestamp, one is soil temp depth, and one is numeric temperature value; 12 soil depths over two profiles in data set

#Creates numeric vector of the correct length with all of the soil temperature measurement depths in cm, repeated once for each row of data collected

# # To view all soil temperature variables in dataset
# print(grep("^TS_1", names(df), value = TRUE))

#Uses depth values in cm for easy coercion to numeric later
ts_columns <- rep(c("0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100"), nrow(df_23_24))

#Picks columns to move into new dataframe; 5 cm lost to make geom_raster work, could linearly interpolate or use geom_tile later?
df_soiltemp = select(df_23_24, TIMESTAMP, grep("^TS_1", names(df), value = TRUE), -TS_1_05_1) 

#Changes column names to line up with numeric depth values
colnames(df_soiltemp) = c("Time", "10", "0", "20", "30", "40", "50", "60", "70", "80", "90", "100")

# Uses linear interpolation to fill NAs in data to create smooth plot
for (col in c("10", "0", "20", "30", "40", "50", "60", "70", "80", "90", "100")) {
  df_soiltemp[[col]] <- na.locf(df_soiltemp[[col]], fromLast = TRUE) # Fill leading NAs
  df_soiltemp[[col]] <- na.locf(df_soiltemp[[col]]) # Fill trailing NAs
  df_soiltemp[[col]] <- na.approx(df_soiltemp[[col]])
}

#repeats every row of the dataframe 11 times
df_soiltemp <- df_soiltemp %>%
  slice(rep(1:n(), each = 11)) %>%
  bind_cols(ts_columns)

names(df_soiltemp)[13] <- "Depth"

#creates empty temp variable to fill with temp values
df_soiltemp$Temperature = NA


#Move corresponding temperature values into the temperature column, them remove unneccesary columns
df_soiltemp <- df_soiltemp %>%
  rowwise() %>%
  mutate(Temperature = ifelse(Depth %in% colnames(df_soiltemp), get(Depth), NA)) %>%
  ungroup() %>%
  select(-c("10", "0", "20", "30", "40", "50", "60", "70", "80", "90", "100"))

df_soiltemp$Depth = as.numeric(df_soiltemp$Depth)

summary(df_soiltemp)


```

## Create Plot 

```{r}
# pal = c('red','orange','yellow','cyan','lightblue','blue','purple','violet')
# pal = c('violet','violet','purple','blue','lightblue','cyan','green','yellow','orange','red','red')
df_soiltemp$doy = format(df_soiltemp$Time,'%j')
df_soiltemp$year = format(df_soiltemp$Time,'%Y')

avg = df_soiltemp %>%
  group_by(doy,year,Depth) %>%
  summarise(Temperature = mean(Temperature,na.rm=T),
            Time = mean(Time,na.rm = T))
summary(avg)

# Creates new, continuous date column to use as X variable in the plot - time averaging was giving us weird gaps
avg$date = as.POSIXct(paste(avg$doy,avg$year,sep = "-"),format="%j-%Y",tz="UTC")

soiltemp <- ggplot(data = avg)+
  theme_bw()+
  aes(x=date, y=-Depth, fill= Temperature)+
  #geom_pointrange(aes(x= Time, y= -Depth, ymin = -100, ymax = 0, color = Temperature))+
  geom_raster(data = avg, interpolate = TRUE)+
  scale_fill_gradient2(low = c('pink','violet','purple','blue'),mid = 'cyan',high = c('green','yellow','orange','red'),midpoint = 0,
  limits = c(-15,20),
  breaks = c(-10, 0, 10, 20),
  labels = c("-10", "0", "10", "20+"),
  name = expression("Temperature ("*degree*"C)"),
  oob = scales::squish)+
  theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14), legend.text = element_text(size = 12))+
  scale_y_continuous(name = "Depth (cm)",
    # trans = "reverse",  # Reverses the direction of the axis
    breaks = seq(0, -100, by = -10),  # Sets breaks for each 10 cm
    labels = seq(0, 100, by = 10),
    expand = c(0,0)
    )+
  scale_x_datetime(
    name = "",
    expand = c(0,0),
    breaks = seq(as.POSIXct("2022-10-01"), as.POSIXct("2024-10-01"), by = "3 months"),
                    date_labels = "%b %Y"
                   )
# +
#   geom_vline(xintercept = as.POSIXct("2024-05-01"), color = "black", linewidth = 1.5)+
#   geom_vline(xintercept = as.POSIXct("2023-05-01"), color = "black", linewidth = 1.5)

soiltemp

#hist(df_soiltemp$Temperature)
##Stop temp scale at 20, make 20+ its own color to help with skew

# png(filename = './soiltempheatmap.png',width = 10,height = 4,units = 'in',res = 2000)
# soiltemp
# dev.off()
  

```