---
title: "Soil Temperature Exponential Model"
author: "Dani Trangmoe"
date: "`r Sys.Date()`"
output: html_document
---


```{r, include=FALSE}
rm(list = ls())
Sys.setenv(TZ = "UTC")

library(data.table)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(gridExtra)
library(patchwork)
```


# Load data 

```{r}

df_avg_y1 <- fread('./year1_daily_avg.csv')
df_avg_y2 <- fread('./year2_daily_avg.csv')
df_avg_23_24 <- fread('./bothyears_daily_avg.csv')

#Creates dataframe with both years of data
df_merge <- merge(df_avg_y1, df_avg_y2, by = "DOY", suffixes = c(".y1", ".y2"))

#dataframe with spring removed


df_nospring <- df_avg_23_24 %>%
  filter(season_name != "Snow Melt")


```

#  Soil Temperature Relationship

Plots 6 and 7 for Ameriflux poster

### Create Exp. Model
```{r}

###Both years

#co2
exp_model <- nls(FC_night ~ a * exp(b * TS_1_0_1), data = df_avg_23_24, start = list(a = 1, b = 0.1))

# Generate predicted values
df_avg_23_24$predicted <- predict(exp_model, newdata = df_avg_23_24)


#ch4
exp_model_ch4 <- nls(FCH4 ~ a * exp(b * TS_1_0_1), data = df_avg_23_24, start = list(a = 1, b = 0.1))

# Generate predicted values
df_avg_23_24$predicted_ch4 <- predict(exp_model_ch4, newdata = df_avg_23_24)



####Both years, spring removed

#co2
exp_model_ns <- nls(FC_night ~ a * exp(b * TS_1_0_1), data = df_nospring, start = list(a = 1, b = 0.1))

# Generate predicted values
df_nospring$predicted <- predict(exp_model_ns, newdata = df_nospring)


#ch4
exp_model_ch4_ns <- nls(FCH4 ~ a * exp(b * TS_1_0_1), data = df_nospring, start = list(a = 1, b = 0.1))

# Generate predicted values
df_nospring$predicted_ch4 <- predict(exp_model_ch4_ns, newdata = df_nospring)



# ### Year 1
# 
# #co2
# exp_model.y1 <- nls(FC_night.y1 ~ a * exp(b * TS_1_0_1.y1), data = df_merge, start = list(a = 1, b = 0.1))
# 
# # Generate predicted values
# df_merge$predicted.y1 <- predict(exp_model.y1, newdata = df_merge)
# 
# 
# 
# #ch4
# exp_model_ch4.y1 <- nls(FCH4.y1 ~ a * exp(b * TS_1_0_1.y1), data = df_merge, start = list(a = 1, b = 0.1))
# 
# # Generate predicted values
# df_merge$predicted_ch4.y1 <- predict(exp_model_ch4.y1, newdata = df_merge)
# 
# 
# ### Year 2
# 
# exp_model.y2 <- nls(FC_night.y2 ~ a * exp(b * TS_1_0_1.y2), data = df_merge, start = list(a = 1, b = 0.1))
# 
# # Generate predicted values
# df_merge$predicted.y2 <- predict(exp_model.y2, newdata = df_merge)
# 
# #ch4
# exp_model_ch4.y2 <- nls(FCH4.y2 ~ a * exp(b * TS_1_0_1.y2), data = df_merge, start = list(a = 1, b = 0.1))
# 
# # Generate predicted values
# df_merge$predicted_ch4.y2 <- predict(exp_model_ch4.y2, newdata = df_merge)


```

## R Squared Values 

```{r}


# R squared values

r_squared <- function(model, column) {
  
  RSS <- sum(residuals(model)^2) # Residual sum of sqares
  TSS <- sum((column - mean(column, na.rm = TRUE))^2, na.rm = TRUE) # ToTS_1_0_1l sum of squares
  
  return(1-(RSS/TSS)) # R squared
  
  
}

#Full Year
rsq_co2 <- r_squared(exp_model, df_avg_23_24$FC_night)
rsq_ch4 <- r_squared(exp_model_ch4, df_avg_23_24$FCH4)

#No Spring
rsq_co2_ns <- r_squared(exp_model_ns, df_nospring$FC_night)
rsq_ch4_ns <- r_squared(exp_model_ch4_ns, df_nospring$FCH4)


```

### Plots


Plots flux variables vs. 5cm soil temp to visualize temperature/co2 flux relationship

Temp relationship plots with daily averages

```{r}
#Both Years CO2

co2model <- ggplot(data=df_avg_23_24)+
  theme_bw()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_point(aes(x=TS_1_0_1, y=FC_night, col = DOY, shape = factor(year)))+
  geom_line(aes(x = TS_1_0_1, y = predicted))+
  scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression(""),
    y = expression("Half-hourly CO "[2] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("Nighttime CO"[2] * " Flux vs. Soil Temperature"))+
  scale_shape_manual(name = "Year", values = c(16, 17))+
  scale_x_continuous(limits=c(-11,14))+
  scale_y_continuous(limits=c(-0.5,2.5))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_co2, 2)),
           size = 5)

co2model






#Methane vs. soil temp

ch4model <- ggplot(data=df_avg_23_24)+
  geom_vline(xintercept=0)+
  theme_bw()+
  geom_point(aes(x=TS_1_0_1, y=FCH4*(1/1000), col = DOY,  shape = factor(year)))+
  geom_line(aes(x = TS_1_0_1, y = predicted_ch4*(1/1000)))+
scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression(""),
    y = expression("Half-hourly CH "[4] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("CH"[4] * " Flux vs. Soil Temperature")
  )+
  scale_x_continuous(limits = c(-11, 14))+
  scale_y_continuous(limits = c(-0.02, .10))+
  scale_shape_manual(name = "Year", values = c(16, 17))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_ch4, 2)),
           size = 5)

ch4model

# png(filename = './modelgrid.png',width = 9.3,height = 5.9,units = 'in',res = 2000)
# grid.arrange(co2model, ch4model, nrow = 1)
# dev.off()


```


With Spring removed:

```{r}

co2model_ns <- ggplot(data=df_nospring)+
  theme_bw()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_point(aes(x=TS_1_0_1, y=FC_night, col = DOY, shape = factor(year)))+
  geom_line(aes(x = TS_1_0_1, y = predicted))+
  scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression("5cm Soil Temperature ("*degree*"C)"),
    y = expression("Half-hourly CO "[2] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("Nighttime CO"[2] * " Flux vs. Soil Temperature, Snow Melt Data Removed"))+
  scale_shape_manual(name = "Year", values = c(16, 17))+
  scale_x_continuous(limits=c(-11,14))+
  scale_y_continuous(limits=c(-0.5,2.5))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_co2_ns, 2)),
           size = 5)

co2model_ns






#Methane vs. soil temp

ch4model_ns <- ggplot(data=df_nospring)+
  geom_vline(xintercept=0)+
  theme_bw()+
  geom_point(aes(x=TS_1_0_1, y=FCH4*(1/1000), col = DOY,  shape = factor(year)))+
  geom_line(aes(x = TS_1_0_1, y = predicted_ch4*(1/1000)))+
scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression("5cm Soil Temperature ("*degree*"C)"),
    y = expression("Half-hourly CH "[4] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression(atop("CH"[4] * " Flux vs. Soil Temperature", "Snow Melt Data Removed"))
  )+
  scale_x_continuous(limits = c(-11, 14))+
  scale_y_continuous(limits = c(-0.02, .10))+
  scale_shape_manual(name = "Year", values = c(16, 17))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_ch4_ns, 2)),
           size = 5)

ch4model_ns


# 
# png(filename = './modelgridco2.png',width = 7,height = 10,units = 'in',res = 2000)
# grid.arrange(co2model, co2model_ns, nrow = 2)
# dev.off()
# 
# png(filename = './modelgridch4.png',width = 7,height = 10,units = 'in',res = 2000)
# grid.arrange(ch4model, ch4model_ns, nrow = 2)
# dev.off()

png(filename = './modelgridall.png',width = 10,height = 10,units = 'in',res = 2000)
co2model + ch4model + co2model_ns + ch4model_ns + plot_layout(guides = "collect", axes = "collect")
dev.off()




```


## Individual Seasons

```{r}


df_spring <- df_avg_23_24 %>%
  filter(season_name == "Snow Melt")

df_gs <- df_avg_23_24 %>%
  filter(season_name == "Growing Season")

df_fall <- df_avg_23_24 %>%
  filter(season_name == "Fall Senescence")

df_winter <- df_avg_23_24 %>%
  filter(season_name == "Winter")
```

Exponential Models
```{r}

## Spring 

#co2
exp_model_spring <- nls(FC_night ~ a * exp(b * TS_1_0_1), data = df_spring, start = list(a = 1, b = 0.1))
df_spring$predicted <- predict(exp_model_spring, newdata = df_spring)


#ch4
exp_model_ch4_spring <- nls(FCH4 ~ a * exp(b * TS_1_0_1), data = df_spring, start = list(a = 1, b = 0.1))
df_spring$predicted_ch4 <- predict(exp_model_ch4_spring, newdata = df_spring)

## gs 

#co2
exp_model_gs <- nls(FC_night ~ a * exp(b * TS_1_0_1), data = df_gs, start = list(a = 1, b = 0.1))
df_gs$predicted <- predict(exp_model_gs, newdata = df_gs)


#ch4
exp_model_ch4_gs <- nls(FCH4 ~ a * exp(b * TS_1_0_1), data = df_gs, start = list(a = 1, b = 0.1))
df_gs$predicted_ch4 <- predict(exp_model_ch4_gs, newdata = df_gs)

## fall 

#co2
exp_model_fall <- nls(FC_night ~ a * exp(b * TS_1_0_1), data = df_fall, start = list(a = 1, b = 0.1))
df_fall$predicted <- predict(exp_model_fall, newdata = df_fall)


#ch4
exp_model_ch4_fall <- nls(FCH4 ~ a * exp(b * TS_1_0_1), data = df_fall, start = list(a = 1, b = 0.1))
df_fall$predicted_ch4 <- predict(exp_model_ch4_fall, newdata = df_fall)

## winter

#co2
exp_model_winter<- nls(FC_night ~ a * exp(b * TS_1_0_1), data = df_winter, start = list(a = 1, b = 0.1))
df_winter$predicted <- predict(exp_model_winter, newdata = df_winter)


#ch4
exp_model_ch4_winter<- nls(FCH4 ~ a * exp(b * TS_1_0_1), data = df_winter, start = list(a = 1, b = 0.1))
df_winter$predicted_ch4 <- predict(exp_model_ch4_winter, newdata = df_winter)

```


linear Models
```{r}

## Spring 

#co2
lm_model_spring <- lm((FC_night ~ TS_1_0_1), data = df_spring)
df_spring$predicted_lm <- predict(lm_model_spring, newdata = df_spring)


#ch4
lm_model_ch4_spring <- lm((FCH4 ~TS_1_0_1), data = df_spring)
df_spring$predicted_ch4_lm <- predict(lm_model_ch4_spring, newdata = df_spring)

## gs 

#co2
lm_model_gs <- lm((FC_night ~TS_1_0_1), data = df_gs)
df_gs$predicted_lm <- predict(lm_model_gs, newdata = df_gs)


#ch4
lm_model_ch4_gs <- lm((FCH4 ~TS_1_0_1), data = df_gs)
df_gs$predicted_ch4_lm <- predict(lm_model_ch4_gs, newdata = df_gs)

## fall 

#co2
lm_model_fall <- lm((FC_night ~TS_1_0_1), data = df_fall)
df_fall$predicted_lm <- predict(lm_model_fall, newdata = df_fall)


#ch4
lm_model_ch4_fall <- lm((FCH4 ~TS_1_0_1), data = df_fall)
df_fall$predicted_ch4_lm <- predict(lm_model_ch4_fall, newdata = df_fall)

## winter

#co2
lm_model_winter<- lm((FC_night ~TS_1_0_1), data = df_winter)
df_winter$predicted_lm <- predict(lm_model_winter, newdata = df_winter)


#ch4
lm_model_ch4_winter<- lm((FCH4 ~TS_1_0_1), data = df_winter)
df_winter$predicted_ch4_lm <- predict(lm_model_ch4_winter, newdata = df_winter)

```


R squared vals

```{r}

# #rerun if needed
# r_squared <- function(model, column) {
#   
#   RSS <- sum(residuals(model)^2) # Residual sum of sqares
#   TSS <- sum((column - mean(column, na.rm = TRUE))^2, na.rm = TRUE) # ToTS_1_0_1l sum of squares
#   
#   return(1-(RSS/TSS)) # R squared
#   
#   
# }

# Exp Models

#Spring
rsq_co2_spring <- r_squared(exp_model_spring, df_spring$FC_night)
rsq_ch4_spring <- r_squared(exp_model_ch4_spring, df_spring$FCH4)

#gs
rsq_co2_gs <- r_squared(exp_model_gs, df_gs$FC_night)
rsq_ch4_gs <- r_squared(exp_model_ch4_gs, df_gs$FCH4)

#fall
rsq_co2_fall <- r_squared(exp_model_fall, df_fall$FC_night)
rsq_ch4_fall <- r_squared(exp_model_ch4_fall, df_fall$FCH4)

#winter
rsq_co2_winter <- r_squared(exp_model_winter, df_winter$FC_night)
rsq_ch4_winter <- r_squared(exp_model_ch4_winter, df_winter$FCH4)





# Linear Models

#Spring
rsq_lm_co2_spring <- r_squared(lm_model_spring, df_spring$FC_night)
rsq_lm_ch4_spring <- r_squared(lm_model_ch4_spring, df_spring$FCH4)

#gs
rsq_lm_co2_gs <- r_squared(lm_model_gs, df_gs$FC_night)
rsq_lm_ch4_gs <- r_squared(lm_model_ch4_gs, df_gs$FCH4)

#fall
rsq_lm_co2_fall <- r_squared(lm_model_fall, df_fall$FC_night)
rsq_lm_ch4_fall <- r_squared(lm_model_ch4_fall, df_fall$FCH4)

#winter
rsq_lm_co2_winter <- r_squared(lm_model_winter, df_winter$FC_night)
rsq_lm_ch4_winter <- r_squared(lm_model_ch4_winter, df_winter$FCH4)



```

```{r}

co2model_spring <- ggplot(data=df_spring)+
  theme_bw()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_point(aes(x=TS_1_0_1, y=FC_night, col = DOY, shape = factor(year)))+
  geom_line(aes(x = TS_1_0_1, y = predicted))+
  scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression("Soil Temperature ("*degree*"C)"),
    y = expression("Half-hourly CO "[2] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("Nighttime CO"[2] * " Flux vs. Soil Temperature, Spring"))+
  scale_shape_manual(name = "Year", values = c(16, 17))+
  scale_x_continuous(limits=c(-11,14))+
  scale_y_continuous(limits=c(-0.5,2.5))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_co2_spring, 2)),
           size = 5)

co2model_spring

co2model_gs <- ggplot(data=df_gs)+
  theme_bw()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_point(aes(x=TS_1_0_1, y=FC_night, col = DOY, shape = factor(year)))+
  geom_line(aes(x = TS_1_0_1, y = predicted))+
  scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression("Soil Temperature ("*degree*"C)"),
    y = expression("Half-hourly CO "[2] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("Nighttime CO"[2] * " Flux vs. Soil Temperature, Growing Season"))+
  scale_shape_manual(name = "Year", values = c(16, 17))+
  scale_x_continuous(limits=c(-11,14))+
  scale_y_continuous(limits=c(-0.5,2.5))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_co2_gs, 2)),
           size = 5)

co2model_gs

co2model_fall <- ggplot(data=df_fall)+
  theme_bw()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_point(aes(x=TS_1_0_1, y=FC_night, col = DOY, shape = factor(year)))+
  geom_line(aes(x = TS_1_0_1, y = predicted))+
  scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression("Soil Temperature ("*degree*"C)"),
    y = expression("Half-hourly CO "[2] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("Nighttime CO"[2] * " Flux vs. Soil Temperature, Fall"))+
  scale_shape_manual(name = "Year", values = c(16, 17))+
  scale_x_continuous(limits=c(-11,14))+
  scale_y_continuous(limits=c(-0.5,2.5))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_co2_fall, 2)),
           size = 5)

co2model_fall

co2model_winter <- ggplot(data=df_winter)+
  theme_bw()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_point(aes(x=TS_1_0_1, y=FC_night, col = DOY, shape = factor(year)))+
  geom_line(aes(x = TS_1_0_1, y = predicted))+
  scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression("Soil Temperature ("*degree*"C)"),
    y = expression("Half-hourly CO "[2] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("Nighttime CO"[2] * " Flux vs. Soil Temperature, Winter"))+
  scale_shape_manual(name = "Year", values = c(16, 17))+
  scale_x_continuous(limits=c(-11,14))+
  scale_y_continuous(limits=c(-0.5,2.5))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_co2_winter, 2)),
           size = 5)

co2model_winter



```
