---
title: "timeseries_plots"
author: "Dani Trangmoe"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

rm(list = ls())
Sys.setenv(TZ = "UTC")

library(data.table)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(gridExtra) 

```

Load Dataframe
```{r}

df_avg_23_24 <- fread('./bothyears_daily_avg.csv')
df_23_24 <- fread("./bothyears_HH.csv")

```

# Carbon Timeseries

Plot 1 on ameriflux poster; timeseries of GPP, ER, NEE, and CH4

```{r}

carbonts <- ggplot(data = df_23_24, aes(x=TIMESTAMP))+
  theme_bw()+
  geom_point(aes(y = -GPP_F*60*60*24*(1/1000000)*12, color = "GPP"))+
  geom_point(aes(y = RECO*60*60*24*(1/1000000)*12, color = "Respiration")) +
  geom_point(aes(y = FC_F*60*60*24*(1/1000000)*12, color = "Carbon Flux"))+
  geom_point(aes(y = FCH4_F*60*60*24*(1/1000000000)*12*13, color = "Methane Flux"))+
  geom_hline(yintercept=0, col="black")+
  scale_y_continuous(limits = c(-8, 5), expression('CO'[2]*' Flux (g C'~m^-2~d^-1*')'),
  sec.axis = sec_axis(~ . /13, name = expression('CH'[4]*' Flux (g C'~m^-2~d^-1*')')))+
  scale_color_manual(name = " ",
            values = c("GPP" = "navy", 
                      "Respiration" = "turquoise3", 
                      "Carbon Flux" = "salmon", 
                      "Methane Flux" = "mediumorchid"),
            breaks = c("GPP", "Respiration", 
              "Carbon Flux", "Methane Flux"))+
  scale_x_datetime(name = expression(""), limits = as.POSIXct(c('2022-10-16', '2024-10-19')))

# png(filename = './carbonts.png',width = 10.96,height = 3.67,units = 'in',res = 2000)
# carbonts
# dev.off()

```


# Soil Temp Timeseries 

```{r}

soiltempts <- ggplot(data = df_avg_23_24)+ theme_bw()+
  geom_hline(yintercept = 0)+
  geom_line(aes(day,TS_2_0_1,color='0 cm'))+
  geom_line(aes(day,TS_2_05_1,color='5 cm'))+
  geom_line(aes(day,TS_2_1_1,color='10 cm'))+
  geom_line(aes(day,TS_2_2_1,color='20 cm'))+  
  geom_line(aes(day,TS_2_3_1,color='30 cm'))+
  geom_line(aes(day,TS_2_4_1,color='40 cm'))+
  geom_line(aes(day,TS_2_5_1,color='50 cm'))+
  geom_line(aes(day,TS_2_6_1,color='60 cm'))+
  geom_line(aes(day,TS_2_7_1,color='70 cm'))+
  geom_line(aes(day,TS_2_8_1,color='80 cm'))+
  geom_line(aes(day,TS_2_9_1,color='90 cm'))+
  geom_line(aes(day,TS_2_10_1,color='100 cm'))+
  scale_y_continuous(expression("Soil Temperature ("*degree*"C)"))+
  scale_x_date(name = expression(""), 
                   breaks = seq(as.Date("2022-10-01"), as.Date("2024-10-01"), by = "3 months"),
                   date_labels = "%b %Y") +
  scale_color_manual(values = c("0 cm" = "darkgreen", "5 cm" = "pink", "10 cm" = "blue", "20 cm" = "orange", "30 cm" = "hotpink", "40 cm" = "tan", "50 cm" = "brown", "60 cm" = "purple", "70 cm" = "cyan", "80 cm" = "magenta", "90 cm" = "yellow", "100 cm" = "gray"),breaks = c("0 cm", "5 cm", "10 cm", "20 cm", "30 cm", "40 cm", "50 cm", "60 cm", "70 cm", "80 cm", "90 cm", "100 cm"), guide = guide_legend(title = NULL))


# png(filename = './soiltempts.png',width = 10.96,height = 3.67,units = 'in',res = 2000)
# soiltempts
# dev.off()
```

# Winter Timeseries
```{r}

df_avg_winter <- df_avg_23_24[df_avg_23_24$season %in% c("Winter 2024", "Winter 2023"), ]

df_avg_winter$D_SNOW[19] <- NA

## Add day of winter column by subtracting/adding to DOY, custom add dates (Jan 1, Feb 1)

## Day 1 of winter = DOY 300
df_avg_winter$DOW <- df_avg_winter$DOY

for (i in seq_len(nrow(df_avg_winter))) {
  if (df_avg_winter$DOY[i] > 300) {
    
    df_avg_winter$DOW[i] <- df_avg_winter$DOW[i] - 300
  }
  
  if (df_avg_winter$DOY[i] <= 300 & df_avg_winter$DOY[i] > 200) {
    
    df_avg_winter$D_SNOW[i] <- NA
  }

  
  if (df_avg_winter$DOY[i] <= 300) {
    
    df_avg_winter$DOW[i] <- df_avg_winter$DOW[i] + 65
  }
}

#dataframe to label days of winter as months

first_of_month <- data.frame(
  DOW = c(65, 96, 124, 155, 185, 216, 246, 277, 308, 338, 4, 34),
  Label = c("Jan 1", "Feb 1", "Mar 1", "Apr 1", "May 1", "Jun 1", "Jul 1", "Aug 1", "Sep 1", "Oct 1", "Nov 1", "Dec 1")
)

df_avg_winter$year <- as.factor(df_avg_winter$year)

df_avg_winter$airdiff <- df_avg_winter$TA-df_avg_winter$TS_2_05_1

#needs axis labels for dashed-dotted line
winterts <- ggplot(data = df_avg_winter)+
  theme_bw()+
  geom_line(aes(x = DOW, y = TS_2_05_1, color = year, linetype = "Soil T"))+
  geom_line(aes(x = DOW, y = TA, color = year, linetype = "Air T"))+
  scale_x_continuous(limits = c(0, 200),
    breaks = first_of_month$DOW,
    labels = first_of_month$Label)+ 
  scale_color_manual(name = " ",
            values = c("2024" = "salmon",
                      "2023" = "turquoise3"),
            breaks = c("2024", "2023"))+
  scale_linetype_manual(name = " ",
                        values = c("Soil T" = "solid",
                          "Air T"="twodash"))+
  labs(
    x = expression(" "),
    y = expression("Temp ("*degree*"C)")
  )

# Ambient temp is dominant trend here, not interesting
ggplot(data = df_avg_winter)+
  theme_bw()+
  geom_line(aes(x = DOW, y = airdiff, color = year))+
  scale_x_continuous(limits = c(0, 200),
    breaks = first_of_month$DOW,
    labels = first_of_month$Label)+
  scale_color_manual(name = " ",
            values = c("2024" = "salmon",
                      "2023" = "turquoise3"),
            breaks = c("2024", "2023"))+
  labs(
    x = expression(" "),
    y = expression("Temp ("*degree*"C)")
  )

wintersd <- ggplot(data = df_avg_winter)+
  theme_bw()+
  geom_line(aes(x = DOW, y = D_SNOW, color = year))+
  scale_x_continuous(limits = c(0, 200),
    breaks = first_of_month$DOW,
    labels = first_of_month$Label)+     
  scale_color_manual(name = " ",
            values = c("2024" = "salmon", 
                      "2023" = "turquoise3"),
            breaks = c("2024", "2023"))+ 
  labs(
    x = expression(" "),
    y = expression("Snow Depth (cm)")
  )

png(filename = './winterts.png',width = 8,height = 6,units = 'in',res = 2000)
grid.arrange(wintersd, winterts, nrow = 2)
dev.off()


```

