---
title: "timeseries_plots"
author: "Dani Trangmoe"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

rm(list = ls())
Sys.setenv(TZ = "UTC")

library(data.table)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(gridExtra) 
library(patchwork)
library(plotrix) # standard error function

```

Load Dataframe
```{r}

df_avg_23_24 <- fread('./output_files/three_years_daily_avg.csv')
df_23_24 <- fread("./output_files/three_years_HH.csv")

```

# Carbon Timeseries

Timeseries of GPP, ER, NEE, and CH4

```{r}

carbonts <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  geom_point(aes(y = FC_F*60*60*24*(1/1e6)*12, shape = "Gapfilled"), color = "navy")+
  geom_point(aes(y = FC*60*60*24*(1/1e6)*12, shape = "Measured"), color = "navy")+
  geom_hline(yintercept=0, col="black")+
  scale_y_continuous(limits = c(-3.2, 1.4), expression('NEE (gC-CO'[2]~m^-2~d^-1*')'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"), date_labels = "%b %Y")+
  scale_shape_manual(name = NULL,
            values = c("Gapfilled" = 1,
                      "Measured" = 16),
            breaks = c("Gapfilled", "Measured"))

carbonts

methanets <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  geom_point(aes(y = FCH4_F*60*60*24*(1/1e9)*12*13, shape = "Gapfilled"), color = "mediumorchid")+
  geom_point(aes(y = FCH4*60*60*24*(1/1e9)*12*13, shape = "Measured"), color = "mediumorchid")+
  geom_hline(yintercept=0, col="black")+
  scale_y_continuous(limits = c(-0.3, 1.5), expression('CH'[4]*' Flux (gC-CH'[4]~m^-2~d^-1*')'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"),
                   date_labels = "%b %Y")+
  scale_shape_manual(name = NULL,
            values = c("Gapfilled" = 1, 
                      "Measured" = 16),
            breaks = c("Gapfilled", "Measured"),
            guide = F)

methanets

# png(filename = './png/fluxts.png',width = 10,height = 6,units = 'in',res = 2000)
# carbonts/methanets + plot_layout(guides = "collect", axes = "collect")
# dev.off()

```


# Soil Temp Timeseries 

```{r}

soiltempts <- ggplot(data = df_avg_23_24)+ theme_bw()+
  geom_hline(yintercept = 0)+
  geom_line(aes(day,TS_2_0_1,color='0 cm'))+
  geom_line(aes(day,TS_2_05_1,color='5 cm'))+
  geom_line(aes(day,TS_2_1_1,color='10 cm'))+
  geom_line(aes(day,TS_2_2_1,color='20 cm'))+  
  geom_line(aes(day,TS_2_3_1,color='30 cm'))+
  geom_line(aes(day,TS_2_4_1,color='40 cm'))+
  geom_line(aes(day,TS_2_5_1,color='50 cm'))+
  geom_line(aes(day,TS_2_6_1,color='60 cm'))+
  geom_line(aes(day,TS_2_7_1,color='70 cm'))+
  geom_line(aes(day,TS_2_8_1,color='80 cm'))+
  geom_line(aes(day,TS_2_9_1,color='90 cm'))+
  geom_line(aes(day,TS_2_10_1,color='100 cm'))+
  scale_y_continuous(expression("Soil Temperature ("*degree*"C)"))+
  scale_x_date(limits = as.Date(c("2022-10-01","2025-09-10")),
               name = expression(""), 
                   breaks = seq(as.Date("2022-10-01"), as.Date("2025-10-01"), by = "3 months"),
                   date_labels = "%b %Y") +
  scale_color_manual(values = c("0 cm" = "darkgreen", "5 cm" = "pink", "10 cm" = "blue", "20 cm" = "orange", "30 cm" = "hotpink", "40 cm" = "tan", "50 cm" = "brown", "60 cm" = "purple", "70 cm" = "cyan", "80 cm" = "magenta", "90 cm" = "yellow", "100 cm" = "gray"),breaks = c("0 cm", "5 cm", "10 cm", "20 cm", "30 cm", "40 cm", "50 cm", "60 cm", "70 cm", "80 cm", "90 cm", "100 cm"), guide = guide_legend(title = NULL))

soiltempts

# png(filename = './png/soiltempts.png',width = 10.96,height = 3.67,units = 'in',res = 2000)
# soiltempts
# dev.off()
```

# Setup

Shade data

```{r}

# Spring
thaw_23 <- data.frame(
  xmin = as.Date("2023-05-04"),
  xmax = as.Date("2023-06-11"),
  ymin = -Inf,
  ymax = Inf,
  label = "Spring Thaw"
)

thaw_24 <- data.frame(
  xmin = as.Date("2024-05-14"),
  xmax = as.Date("2024-06-17"),
  ymin = -Inf,
  ymax = Inf,
  label = "Spring Thaw"
)

thaw_25 <- data.frame(
  xmin = as.Date("2025-05-22"),
  xmax = as.Date("2025-06-17"),
  ymin = -Inf,
  ymax = Inf,
  label = "Spring Thaw"
)


#Fall 

fall_22 <- data.frame(
  xmin = as.Date("2022-09-19"),
  xmax = as.Date("2022-10-15"),
  ymin = -Inf,
  ymax = Inf,
  label = "Fall Senescence"
)

fall_23 <- data.frame(
  xmin = as.Date("2023-09-06"),
  xmax = as.Date("2023-10-22"),
  ymin = -Inf,
  ymax = Inf,
  label = "Fall Senescence"
)

fall_24 <- data.frame(
  xmin = as.Date("2024-09-13"),
  xmax = as.Date("2024-10-19"),
  ymin = -Inf,
  ymax = Inf,
  label = "Fall Senescence"
)


#Winter

winter_22 <- data.frame(
  xmin = as.Date("2022-10-15"),
  xmax = as.Date("2023-05-05"),
  ymin = -Inf,
  ymax = Inf,
  label = "Winter"
)

winter_23 <- data.frame(
  xmin = as.Date("2023-10-22"),
  xmax = as.Date("2024-05-14"),
  ymin = -Inf,
  ymax = Inf,
  label = "Winter"
)

winter_24 <- data.frame(
  xmin = as.Date("2024-10-19"),
  xmax = as.Date("2025-05-22"),
  ymin = -Inf,
  ymax = Inf,
  label = "Winter"
)


# Growing season
gs_23 <- data.frame(
  xmin = as.Date("2023-09-06"),
  xmax = as.Date("2023-06-11"),
  ymin = -Inf,
  ymax = Inf,
  label = "Growing Season"
)

gs_24 <- data.frame(
  xmin = as.Date("2024-09-13"),
  xmax = as.Date("2024-06-17"),
  ymin = -Inf,
  ymax = Inf,
  label = "Growing Season"
)

gs_25 <- data.frame(
  xmin = as.Date("2025-09-10"),
  xmax = as.Date("2025-06-17"),
  ymin = -Inf,
  ymax = Inf,
  label = "Growing Season"
)


```


## Met Timeseries
```{r}

co2_ts <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  
    geom_rect(data = thaw_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = gs_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = fall_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
  
        geom_rect(data = winter_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
  
  geom_point(aes(y = FC_F*60*60*24*(1/1e6)*12, shape = "Gapfilled"), color = "navy")+
  geom_point(aes(y = FC*60*60*24*(1/1e6)*12, shape = "Measured"), color = "navy")+
  geom_hline(yintercept=0, col="black")+
  geom_vline(xintercept = as.Date("2022-09-19"), col = "black")+
  geom_vline(xintercept = as.Date("2023-09-06"), col = "black")+
  geom_vline(xintercept = as.Date("2024-09-13"), col = "black")+
  geom_vline(xintercept = as.Date("2025-09-10"), col = "black")+
  scale_y_continuous(limits = c(-3.2, 1.4), expression('NEE (gC-CO'[2]~m^-2~d^-1*')'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"), date_labels = "%b %Y")+
  scale_shape_manual(name = NULL,
            values = c("Gapfilled" = 1,
                      "Measured" = 16),
            breaks = c("Gapfilled", "Measured"))+
  scale_fill_manual(name = NULL,
            values = c("Spring Thaw" = "mediumorchid",
                      "Fall Senescence" = "orange",
                      "Winter" = "cyan3",
                      "Growing Season" = "green4"),
            breaks = c("Spring Thaw", "Fall Senescence", "Winter", "Growing Season"))

co2_ts

ch4_ts <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  
    geom_rect(data = thaw_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = gs_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = fall_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
  
        geom_rect(data = winter_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
  
  geom_point(aes(y = FCH4_F*60*60*24*(1/1e9)*12*13, shape = "Gapfilled"), color = "navy")+
  geom_point(aes(y = FCH4*60*60*24*(1/1e9)*12*13, shape = "Measured"), color = "navy")+
  geom_hline(yintercept=0, col="black")+
  geom_vline(xintercept = as.Date("2022-09-19"), col = "black")+
  geom_vline(xintercept = as.Date("2023-09-06"), col = "black")+
  geom_vline(xintercept = as.Date("2024-09-13"), col = "black")+
  geom_vline(xintercept = as.Date("2025-09-10"), col = "black")+
  scale_y_continuous(limits = c(-0.5, 1.4), expression('CH'[4]*' Flux (gC-CH'[4]~m^-2~d^-1*')'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"), date_labels = "%b %Y")+
  scale_shape_manual(name = NULL,
            values = c("Gapfilled" = 1,
                      "Measured" = 16),
            breaks = c("Gapfilled", "Measured"))+
  scale_fill_manual(name = NULL,
            values = c("Spring Thaw" = "mediumorchid",
                      "Fall Senescence" = "orange",
                      "Winter" = "cyan3",
                      "Growing Season" = "green4"),
            breaks = c("Spring Thaw", "Fall Senescence", "Winter", "Growing Season"))

ch4_ts



sw_ts <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  
    geom_rect(data = thaw_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = gs_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = fall_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
  
        geom_rect(data = winter_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
  
  geom_line(aes(y = SW_OUT), color = "navy")+
  #geom_point(aes(y = FC*60*60*24*(1/1e6)*12, shape = "Measured"), color = "navy")+
  geom_hline(yintercept=0, col="black")+
  geom_vline(xintercept = as.Date("2022-09-19"), col = "black")+
  geom_vline(xintercept = as.Date("2023-09-06"), col = "black")+
  geom_vline(xintercept = as.Date("2024-09-13"), col = "black")+
  geom_vline(xintercept = as.Date("2025-09-10"), col = "black")+
  scale_y_continuous(limits = c(-0, 250), expression('Outgoing Shortwave Radiation (W'~m^-2*')'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"), date_labels = "%b %Y")+
  # scale_shape_manual(name = NULL,
  #           values = c("Gapfilled" = 1,
  #                     "Measured" = 16),
  #           breaks = c("Gapfilled", "Measured"))+
  scale_fill_manual(name = NULL,
            values = c("Spring Thaw" = "mediumorchid",
                      "Fall Senescence" = "orange",
                      "Winter" = "cyan3",
                      "Growing Season" = "green4"),
            breaks = c("Spring Thaw", "Fall Senescence", "Winter", "Growing Season"))

sw_ts




snow_ts <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  
    geom_rect(data = thaw_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = gs_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = fall_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
  
        geom_rect(data = winter_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
  
  geom_line(aes(y = D_SNOW), color = "navy")+
  geom_hline(yintercept=0, col="black")+
  geom_vline(xintercept = as.Date("2022-09-19"), col = "black")+
  geom_vline(xintercept = as.Date("2023-09-06"), col = "black")+
  geom_vline(xintercept = as.Date("2024-09-13"), col = "black")+
  geom_vline(xintercept = as.Date("2025-09-10"), col = "black")+
  scale_y_continuous(limits = c(0, 65), expression('Snow Depth (cm)'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"), date_labels = "%b %Y")+
  # scale_shape_manual(name = NULL,
  #           values = c("Gapfilled" = 1,
  #                     "Measured" = 16),
  #           breaks = c("Gapfilled", "Measured"))+
  scale_fill_manual(name = NULL,
            values = c("Spring Thaw" = "mediumorchid",
                      "Fall Senescence" = "orange",
                      "Winter" = "cyan3",
                      "Growing Season" = "green4"),
            breaks = c("Spring Thaw", "Fall Senescence", "Winter", "Growing Season"))

snow_ts


swc_ts <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  
    geom_rect(data = thaw_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = gs_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = fall_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
  
        geom_rect(data = winter_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
  
  geom_line(aes(y = SWC_2_1_1), color = "navy")+
  geom_hline(yintercept=0, col="black")+
  geom_vline(xintercept = as.Date("2022-09-19"), col = "black")+
  geom_vline(xintercept = as.Date("2023-09-06"), col = "black")+
  geom_vline(xintercept = as.Date("2024-09-13"), col = "black")+
  geom_vline(xintercept = as.Date("2025-09-10"), col = "black")+
  scale_y_continuous(limits = c(0, 78), expression('Hummock Soil Water Content (%)'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"), date_labels = "%b %Y")+
  # scale_shape_manual(name = NULL,
  #           values = c("Gapfilled" = 1,
  #                     "Measured" = 16),
  #           breaks = c("Gapfilled", "Measured"))+
  scale_fill_manual(name = NULL,
            values = c("Spring Thaw" = "mediumorchid",
                      "Fall Senescence" = "orange",
                      "Winter" = "cyan3",
                      "Growing Season" = "green4"),
            breaks = c("Spring Thaw", "Fall Senescence", "Winter", "Growing Season"))

swc_ts



temp_ts <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  
    geom_rect(data = thaw_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = gs_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = fall_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
  
        geom_rect(data = winter_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
  
  geom_line(aes(y = TS_2_05_1, linetype = "5cm Soil Temp"), color = "navy")+
  geom_line(aes(y = TA, linetype = "Air Temp"), color = "navy")+
  geom_hline(yintercept=0, col="black")+
  geom_vline(xintercept = as.Date("2022-09-19"), col = "black")+
  geom_vline(xintercept = as.Date("2023-09-06"), col = "black")+
  geom_vline(xintercept = as.Date("2024-09-13"), col = "black")+
  geom_vline(xintercept = as.Date("2025-09-10"), col = "black")+
  scale_y_continuous(limits = c(-40, 20), expression('Temperature ('*degree*'C)'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"), date_labels = "%b %Y")+
  scale_linetype_manual(name = NULL,
            values = c("Air Temp" = "solid",
                      "5cm Soil Temp" = "dashed"),
            breaks = c("Air Temp", "5cm Soil Temp"))+
  scale_fill_manual(name = NULL,
            values = c("Spring Thaw" = "mediumorchid",
                      "Fall Senescence" = "orange",
                      "Winter" = "cyan3",
                      "Growing Season" = "green4"),
            breaks = c("Spring Thaw", "Fall Senescence", "Winter", "Growing Season"))

temp_ts
```


## Flux Timeseries
```{r}

gpp_ts <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  
    geom_rect(data = thaw_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = gs_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = fall_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
  
        geom_rect(data = winter_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
  
  geom_point(aes(y = GPP_F*60*60*24*(1/1e6)*12), color = "navy")+
  geom_hline(yintercept=0, col="black")+
  geom_vline(xintercept = as.Date("2022-09-19"), col = "black")+
  geom_vline(xintercept = as.Date("2023-09-06"), col = "black")+
  geom_vline(xintercept = as.Date("2024-09-13"), col = "black")+
  geom_vline(xintercept = as.Date("2025-09-10"), col = "black")+
  scale_y_continuous(limits = c(-1, 4.2), expression('GPP (g C'~m^-2~d^-1*')'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"), date_labels = "%b %Y")+
  scale_linetype_manual(name = NULL,
            values = c("Air Temp" = "solid",
                      "5cm Soil Temp" = "dashed"),
            breaks = c("Air Temp", "5cm Soil Temp"))+
  scale_fill_manual(name = NULL,
            values = c("Spring Thaw" = "mediumorchid",
                      "Fall Senescence" = "orange",
                      "Winter" = "cyan3",
                      "Growing Season" = "green4"),
            breaks = c("Spring Thaw", "Fall Senescence", "Winter", "Growing Season"))

gpp_ts


reco_ts <- ggplot(data = df_avg_23_24, aes(x=date))+
  theme_bw()+
  
    geom_rect(data = thaw_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = thaw_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Spring Thaw"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = gs_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = gs_25, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Growing Season"),
            alpha = 0.2, inherit.aes = FALSE)+
  
      geom_rect(data = fall_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = fall_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Fall Senescence"),
            alpha = 0.2, inherit.aes = FALSE)+
  
        geom_rect(data = winter_22, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_23, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
      geom_rect(data = winter_24, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Winter"),
            alpha = 0.2, inherit.aes = FALSE)+
  
  geom_point(aes(y = RECO*60*60*24*(1/1e6)*12), color = "navy")+
  geom_hline(yintercept=0, col="black")+
  geom_vline(xintercept = as.Date("2022-09-19"), col = "black")+
  geom_vline(xintercept = as.Date("2023-09-06"), col = "black")+
  geom_vline(xintercept = as.Date("2024-09-13"), col = "black")+
  geom_vline(xintercept = as.Date("2025-09-10"), col = "black")+
  scale_y_continuous(limits = c(-0.3, 2.4), expression('RECO (g C'~m^-2~d^-1*')'))+
  scale_x_date(name = NULL,
                   breaks = seq(as.Date("2022-09-01"), as.Date("2025-09-01"), by = "4 months"), date_labels = "%b %Y")+
  scale_linetype_manual(name = NULL,
            values = c("Air Temp" = "solid",
                      "5cm Soil Temp" = "dashed"),
            breaks = c("Air Temp", "5cm Soil Temp"))+
  scale_fill_manual(name = NULL,
            values = c("Spring Thaw" = "mediumorchid",
                      "Fall Senescence" = "orange",
                      "Winter" = "cyan3",
                      "Growing Season" = "green4"),
            breaks = c("Spring Thaw", "Fall Senescence", "Winter", "Growing Season"))

reco_ts


```



```{r}
png(filename = './png/co2_ts.png',width = 10,height = 3,units = 'in',res = 2000)
co2_ts
dev.off()

png(filename = './png/ch4_ts.png',width = 10,height = 3,units = 'in',res = 2000)
ch4_ts
dev.off()

png(filename = './png/swc_ts.png',width = 10,height = 3,units = 'in',res = 2000)
swc_ts
dev.off()

png(filename = './png/sw_ts.png',width = 10,height = 3,units = 'in',res = 2000)
sw_ts
dev.off()

png(filename = './png/snow_ts.png',width = 10,height = 3,units = 'in',res = 2000)
snow_ts
dev.off()

png(filename = './png/temp_ts.png',width = 10,height = 3,units = 'in',res = 2000)
temp_ts
dev.off()

png(filename = './png/gpp_reco_ts.png',width = 10,height = 6,units = 'in',res = 2000)
gpp_ts / reco_ts + plot_layout(guides = "collect", axes = "collect")
dev.off()


```
