---
title: "Winter Timeseries"
author: "Dani Trangmoe"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

rm(list = ls())
Sys.setenv(TZ = "UTC")

library(data.table)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(gridExtra) 
library(patchwork)
library(plotrix) # standard error function

```

Load Dataframe
```{r}

df_avg_23_24 <- fread('./output_files/three_years_daily_avg.csv')
df_23_24 <- fread("./output_files/three_years_HH.csv")

```



# Winter Timeseries

Create winter dataframe 
```{r}



df_avg_winter <- df_avg_23_24[df_avg_23_24$season %in% c("Winter 2025", "Winter 2024", "Winter 2023"), ]

df_avg_winter$D_SNOW[19] <- NA

## Add day of winter column by subtracting/adding to DOY, custom add dates (Jan 1, Feb 1)

## Day 1 of winter = DOY 300
df_avg_winter$DOW <- df_avg_winter$DOY

for (i in seq_len(nrow(df_avg_winter))) {
  if (df_avg_winter$DOY[i] > 300) {
    
    df_avg_winter$DOW[i] <- df_avg_winter$DOW[i] - 300
  }
  
  if (df_avg_winter$DOY[i] <= 300 & df_avg_winter$DOY[i] > 200) {
    
    df_avg_winter$D_SNOW[i] <- NA
  }

  
  if (df_avg_winter$DOY[i] <= 300) {
    
    df_avg_winter$DOW[i] <- df_avg_winter$DOW[i] + 65
  }
}

#dataframe to label days of winter as months

first_of_month <- data.frame(
  DOW = c(65, 96, 124, 155, 185, 216, 246, 277, 308, 338, 4, 34),
  Label = c("Jan 1", "Feb 1", "Mar 1", "Apr 1", "May 1", "Jun 1", "Jul 1", "Aug 1", "Sep 1", "Oct 1", "Nov 1", "Dec 1")
)

df_avg_winter$season_year <- as.factor(df_avg_winter$season_year)

df_avg_winter$airdiff <- df_avg_winter$TA-df_avg_winter$TS_2_05_1

```

Create monthly averages of winter data

```{r}

df_avg_winter$month <- month(df_avg_winter$date)
summary(df_avg_winter$month)


df_monthly_avg_winter <- df_avg_winter %>%
  group_by(month, full_year)%>%
  summarize(
    nee = round(mean(FC, na.rm = TRUE), 3),
    tair = round(mean(TA, na.rm = TRUE), 2),
    tsoil5 = round(mean(TS_2_05_1, na.rm = TRUE), 2),
    swc = round(mean(SWC_1_1_1, na.rm = TRUE), 2),
    ws = round(mean(WS, na.rm = TRUE), 2),
    ch4 = round(mean(FCH4, na.rm = TRUE), 2), # other variables kept as artifact from old code, maybe add back later
    nee.se = round(std.error(FC, na.rm = TRUE), 2),
    tair.se = round(std.error(TA, na.rm = TRUE), 2),
    tsoil5.se = round(std.error(TS_2_05_1, na.rm = TRUE), 2),
    swc.se = round(std.error(SWC_1_1_1, na.rm = TRUE), 2),
    ws.se = round(std.error(WS, na.rm = TRUE), 2),
    ch4.se = round(std.error(FCH4, na.rm = TRUE), 2)
    ) %>%
  select(c(full_year, month, tair, tair.se, tsoil5, tsoil5.se)) %>%
  pivot_wider(names_from = full_year, values_from = c(tair, tair.se, tsoil5, tsoil5.se))



tair <- ggplot(data = df_monthly_avg_winter)+
  theme_bw()+
  theme(
    plot.background = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1), axis.text.y = element_text(size = 12), 
  axis.title.y = element_text(size = 14),axis.title.x = element_blank(),
  legend.position = "none")+
  geom_line(aes(x = month, y = tair_1, color = "1"))+
  geom_line(aes(x = month, y = tair_2, color = "2"))+
  geom_line(aes(x = month, y = tair_3, color = "3"))+
  geom_point(aes(x = month, y = tair_1, color = "1"))+
  geom_point(aes(x = month, y = tair_2, color = "2"))+
  geom_point(aes(x = month, y = tair_3, color = "3"))+
  geom_errorbar(
    aes(x = month,
        ymin = tair_1 - tair.se_1,
        ymax = tair_1 + tair.se_1,
        color = "1"),
    width = 0.3
  )+
  geom_errorbar(
    aes(x = month,
        ymin = tair_2 - tair.se_2,
        ymax = tair_2 + tair.se_2,
        color = "2"),
    width = 0.3
  )+
    geom_errorbar(
    aes(x = month,
        ymin = tair_3 - tair.se_3,
        ymax = tair_3 + tair.se_3,
        color = "3"),
    width = 0.3
  )+    
  geom_hline(aes(yintercept = 0, color = "black"))+
  scale_x_continuous(breaks = 1:12, labels = month.abb)+
  scale_y_continuous(expression('Air Temperature ('*degree*'C)'))+
  scale_color_manual(name = " ",
            values = c("1" = "turquoise3", 
                      "2" = "salmon",
                      "3" = "navy"),
            breaks = c("1", "2", "3"))
```

# Plot
```{r}


#needs axis labels for dashed-dotted line
winterts <- ggplot(data = df_avg_winter)+
  theme_bw()+
  guides(
    color = guide_legend(order = 1),     # appears first (top)
    linetype = guide_legend(order = 2)   # appears second (below)
  )+
  geom_hline(aes(yintercept = 0))+
  geom_line(aes(x = DOW, y = TS_2_05_1, color = season_year, linetype = "Soil Temp"))+
  geom_line(aes(x = DOW, y = TA, color = season_year, linetype = "Air Temp"), alpha = 0.4)+
  scale_x_continuous(limits = c(0, 200),
    breaks = first_of_month$DOW,
    labels = first_of_month$Label)+ 
  scale_linetype_manual(name = " ",
                        values = c("Soil Temp" = "solid",
                          "Air Temp"="twodash"))+
  scale_color_manual(name = " ",
            values = c("2025" = "navy",
                      "2024" = "salmon",
                      "2023" = "turquoise3"),
            breaks = c("2023", "2024", "2025"))+
  labs(
    x = expression(" "),
    y = expression("Temperature ("*degree*"C)")
  )

winterts

# # Ambient temp is dominant trend here, not interesting
# ggplot(data = df_avg_winter)+
#   theme_bw()+
#   geom_line(aes(x = DOW, y = airdiff, color = year))+
#   scale_x_continuous(limits = c(0, 200),
#     breaks = first_of_month$DOW,
#     labels = first_of_month$Label)+
#   scale_color_manual(name = " ",
#             values = c("2024" = "salmon",
#                       "2023" = "turquoise3"),
#             breaks = c("2024", "2023"))+
#   labs(
#     x = expression(" "),
#     y = expression("Temp ("*degree*"C)")
#   )

wintersd <- ggplot(data = df_avg_winter)+
  theme_bw()+
  guides(
    color = guide_legend(order = 1),
    linetype = guide_legend(order = 2)
  )+
  geom_line(aes(x = DOW, y = D_SNOW, color = season_year), show.legend = FALSE)+
  scale_x_continuous(limits = c(0, 200),
    breaks = first_of_month$DOW,
    labels = first_of_month$Label)+     
  scale_color_manual(name = " ",
            values = c("2025" = "navy",
                      "2024" = "salmon", 
                      "2023" = "turquoise3"),
            breaks = c("2023", "2024", "2025"))+ 
  labs(
    x = expression(" "),
    y = expression("Snow Depth (cm)")
  )

wintersd

png(filename = './png/winterts.png',width = 8,height = 6,units = 'in',res = 2000)
wintersd / winterts + plot_layout(guides = "collect", axes = "collect")
dev.off()


```



