---
title: "combined_soil_temp_and_lrc"
output: html_document
---


``` {r}
rm(list = ls())

library(ggplot2)
library(data.table)
library(openair)
library(bigleaf)
library(dplyr)
library(patchwork)
```


################ LRC #################

Load half-hourly data
```{r}
#load in the CF3 Ameriflux file
df = fread('./output_files/three_years_HH.csv')
```

Create LRC plot
```{r}
# #create a "date" column so it works with Time Average
df$date = df$TIMESTAMP
# df = subset(df,df$date > as.POSIXct('2022-07-01')) #subset to rough beginning of dataset

############################################################################################
# play with conditions where light response is most valid, i.e., after greenup during the growing season
gs = subset(df, df$season_name %in% c("Growing Season") & df$PPFD_IN > 0)
# gs$FC = ifelse(gs$FC < -5 & gs$PPFD_IN < 400,NA,gs$FC)

#gs = subset(df, df$TS_2_05_1 > 5  & df$PPFD_IN > 0)

gs = gs[complete.cases(gs$PPFD_IN),]

gs = gs[complete.cases(gs$FC), ]

#run the light. response curve in bigleaf package
lr = light.response(data = gs,NEE = 'FC',Reco = 'RECO',PPFD = 'PPFD_IN',PPFD_ref = 1500)
fit = lr$m$fitted() #add fitted data
lr$m$fitted()



#−NEE = αPPFD/(1−(PPFD/PPFDref)+αPPFD/GPPref)−Reco
lr_summary <- summary(lr)
lr_summary

#Save parameters for plotting
parameters <- lr_summary$parameters
alpha <- parameters["alpha", "Estimate"]
GPP_ref <- parameters ["GPP_ref", "Estimate"]


gs$FC = ifelse(gs$FC < -5 & gs$PPFD_IN < 400,NA,gs$FC)
gs$lrfit = fit

gs = gs[order(gs$PPFD_IN),]

α = rep(0.016,nrow(gs))
PPFDref = rep(1500,nrow(gs))
GPPref = rep(4.29,nrow(gs))
Reco = gs$RECO
ppfd = gs$PPFD_IN

line = α*ppfd/(1-(ppfd/PPFDref)+α*ppfd/GPPref)-mean(Reco)

mean(gs$RECO)

#plot the fit data vs the real PAR, NEE relationship
lrc <- ggplot(data = gs)+
  theme_bw()+
  theme(
    plot.background = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
    axis.title.y = element_text(size = 14),axis.title.x = element_text(size = 14))+
  geom_hline(aes(yintercept = 0),col = 'black')+
  geom_point(aes(PPFD_IN,FC, col = DOY))+
  scale_color_gradient(low = "navy", high = "salmon", limits = c(1, 365))+
  geom_line(aes(PPFD_IN,line*-1),col='black', linewidth = 1.2)+
  geom_smooth(formula = y ~ α*ppfd/(1-(ppfd/PPFDref)+α*ppfd/GPPref)-Reco,col='black', aes(PPFD_IN,FC),method = 'lm')+
#  geom_line(aes(PPFD_IN,lrfit*-1),col='red')+
#  scale_color_viridis_c()+
  annotate("text", 
           x = Inf, y = Inf, 
           hjust = 1.1, vjust = 1.3,
           label = paste0("\u03B1 = ", round(alpha, 3), "\nGPP ref = ", round(GPP_ref, 2)),
           size = 5)+
  labs(
    y = expression('NEE ('*mu*mol~m^-2~s^-1*')'),
    x = expression('PAR In ('*mu*'mol m'^-2*'s'^-1*')'),
    title = "c) Light Response Curve",
    subtitle = "Growing Season Only")
lrc
```




######################## Soil Temp Models #################################



# Load Daily Avg. Data

```{r}

df_avg_23_24 <- fread('./output_files/three_years_daily_avg.csv')


#dataframe with spring removed

df_nogs <- df_avg_23_24 

#convert methane units here so models work

df_nogs$FCH4 <- df_nogs$FCH4 * (1/1000)

```

#  Soil Temperature Relationship

### Create Exp. Model
```{r}

###Both years

#co2
exp_model <- nls(FC_night ~ a * exp(b * TS_1_0_1), data = df_avg_23_24, start = list(a = 1, b = 0.1))

# Generate predicted values
df_avg_23_24$predicted <- predict(exp_model, newdata = df_avg_23_24)
 
# Get p-value for temperature effect (b parameter) 
p_value_co2 <- summary(exp_model)$coefficients["b", "Pr(>|t|)"]


#ch4
exp_model_ch4 <- nls(FCH4 ~ a * exp(b * TS_1_0_1), data = df_avg_23_24, start = list(a = 1, b = 0.1))

# Generate predicted values
df_avg_23_24$predicted_ch4 <- predict(exp_model_ch4, newdata = df_avg_23_24)

# Get p-value for temperature effect (b parameter) 
p_value_ch4 <- summary(exp_model_ch4)$coefficients["b", "Pr(>|t|)"]


####Both years, spring removed

#co2
exp_model_ngs <- nls(FC_night ~ a * exp(b * TS_1_0_1), data = df_nogs, start = list(a = 1, b = 0.1))

# Generate predicted values
df_nogs$predicted <- predict(exp_model_ngs, newdata = df_nogs)


#ch4
exp_model_ch4_ngs <- nls(FCH4 ~ a * exp(b * TS_1_0_1), data = df_nogs, start = list(a = 1, b = 0.1))

# Generate predicted values
df_nogs$predicted_ch4 <- predict(exp_model_ch4_ngs, newdata = df_nogs)


```

## R Squared Values 

```{r}

r_squared <- function(model) {

  # Get residuals (only for data model actually used)
  resid <- residuals(model)

  # Get fitted values (only for data model actually used)
  fitted_vals <- fitted(model)

  # Back-calculate observed values (only for data model actually used)
  observed <- fitted_vals + resid

  # Now RSS and TSS are from the SAME dataset
  RSS <- sum(resid^2)
  TSS <- sum((observed - mean(observed))^2)

  R2 <- 1 - (RSS / TSS)

  return(R2)
}

#Full Year
rsq_co2 <- r_squared(exp_model)
rsq_ch4 <- r_squared(exp_model_ch4)

#No Spring
rsq_co2_ngs <- r_squared(exp_model_ngs)
rsq_ch4_ngs <- r_squared(exp_model_ch4_ngs)



##parameters
coef_ngs <- coef(exp_model_ngs)
coef_ch4_ngs <- coef(exp_model_ch4_ngs)

a_ngs <- coef_ngs[["a"]]
b_ngs <- coef_ngs[["b"]]

a_ch4_ngs <- coef_ch4_ngs[["a"]]
b_ch4_ngs <- coef_ch4_ngs[["b"]]

```

### Plots

```{r}

label_co2 <- bquote(y == .(round(a_ngs, 2)) * e^{.(round(b_ngs, 2)) * x})

co2model_ngs <- ggplot(data=df_nogs)+
  theme_bw()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_point(aes(x=TS_1_0_1, y=FC_night, col = DOY, #shape = factor(season_year)
                 ))+
  geom_errorbar(
    aes(x = TS_1_0_1,
        ymin = FC_night - FC_night_sd,
        ymax = FC_night + FC_night_sd),
    width = 0.2
  )+
  geom_line(aes(x = TS_1_0_1, y = predicted))+
  scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression("Surface Soil Temperature ("*degree*"C)"),
    y = expression("NEE ("*mu*mol~m^-2~s^-1*")"),
    title = expression("a) Nighttime NEE vs. Soil Temperature"))+
 # scale_shape_manual(name = "Year", values = c(16, 17))+
  scale_x_continuous(limits=c(-11,25))+
  scale_y_continuous(limits=c(-0.5,3))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),
  plot.subtitle = element_text(size = 12, face = "italic"))+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_co2_ngs, 2)),
           size = 5)+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 2.2,
           label = as.expression(label_co2),
           size = 5)

co2model_ngs



#Methane vs. soil temp

label_ch4 <- bquote(y == .(round(a_ch4_ngs, 3)) * e^{.(round(b_ch4_ngs, 3)) * x})

ch4model <- ggplot(data=df_nogs)+
  geom_vline(xintercept=0)+
  geom_hline(yintercept = 0)+
  theme_bw()+
  geom_point(aes(x=TS_1_0_1, y=FCH4, col = DOY,  
                 #shape = factor(year)
                 ))+
  # geom_errorbar(
  #   aes(x = TS_1_0_1,
  #       ymin = FCH4 - FCH4_sd,
  #       ymax = FCH4 + FCH4_sd),
  #   width = 0.2
  # )+
  geom_line(aes(x = TS_1_0_1, y = predicted_ch4))+
scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression("Surface Soil Temperature ("*degree*"C)"),
    y = expression("CH "[4] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("b) CH"[4] * " Flux vs. Soil Temperature")
  )+
  scale_x_continuous(limits = c(-11, 25))+
  scale_y_continuous(limits = c(-0.02, .11))+
  #scale_shape_manual(name = "Year", values = c(15, 16, 17, 18))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),
  plot.subtitle = element_text(size = 12, face = "italic"))+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_ch4_ngs, 2)),
           size = 5)+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 2.2,
           label = as.expression(label_ch4),
           size = 5)

ch4model
```

####################### Combine ##################################
```{r}

png(filename = './png/modelgrid_stats.png',width = 8,height = 10,units = 'in',res = 2000)
co2model_ngs / ch4model / lrc + plot_layout(guides = "collect")
dev.off()


```