---
title: "Q10s"
author: "Dani Trangmoe"
date: "`r Sys.Date()`"
output: html_document
---


```{r, include=FALSE}
rm(list = ls())
Sys.setenv(TZ = "UTC")

library(data.table)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(gridExtra)
library(respirometry)
```


# Load Data 

```{r}

df_23_24 <- fread('./output_files/three_years_HH.csv')


```


# Temperature sensitivity

## CO2

```{r}

# Full year

q10_fc_air <- Q10(R_vec = df_23_24$FC_night, T_vec = df_23_24$TA)
q10_fc_soil <- Q10(R_vec = df_23_24$FC_night, T_vec = df_23_24$TS_1_0_1)



# Only Winter
df_winter <- df_23_24 %>%
  filter(season_name == "Winter")

q10_fc_air_winter <- Q10(R_vec = df_winter$FC_night, T_vec = df_winter$TA)


#No Winter
df_nowinter <- df_23_24 %>%
  filter(season_name != "Winter")

q10_fc_air_nowinter <- Q10(R_vec = df_nowinter$FC_night, T_vec = df_nowinter$TA)

```

## Methane

```{r}

# Full year

q10_fch4_air <- Q10(R_vec = df_23_24$FCH4, T_vec = df_23_24$TA)
q10_fch4_soil <- Q10(R_vec = df_23_24$FCH4, T_vec = df_23_24$TS_1_0_1)


# Only Winter
df_winter <- df_23_24 %>%
  filter(season_name == "Winter")

q10_fch4_air_winter <- Q10(R_vec = df_winter$FCH4, T_vec = df_winter$TA)


#No Winter
df_nowinter <- df_23_24 %>%
  filter(season_name != "Winter")

q10_fch4_air_nowinter <- Q10(R_vec = df_nowinter$FCH4, T_vec = df_nowinter$TA)

```


