---
title: "SWC Exponential Model"
author: "Dani Trangmoe"
date: "`r Sys.Date()`"
output: html_document
---


```{r, include=FALSE}
rm(list = ls())
Sys.setenv(TZ = "UTC")

library(data.table)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(gridExtra)
```


# Load data

```{r}

df_avg_23_24 <- fread('./output_files/three_years_daily_avg.csv')


#dataframe with spring removed

df_nogs <- df_avg_23_24 %>%
  #filter(season_name != "Growing Season")%>%
  filter(SWC_2_2_1 > 70)


```

#  SWC/ER Relationship

### Create Exp. Model
```{r}

###Both years

#co2 - SWC_1_1_1 has best r squared 
exp_model1 <- nls(FC_night ~ a * exp(b * SWC_1_1_1), data = df_avg_23_24, start = list(a = 1, b = 0.1))

# Generate predicted values
df_avg_23_24$predicted1 <- predict(exp_model1, newdata = df_avg_23_24)

exp_model2 <- nls(FC_night ~ a * exp(b * SWC_2_1_1), data = df_avg_23_24, start = list(a = 1, b = 0.1))

# Generate predicted values
df_avg_23_24$predicted2 <- predict(exp_model2, newdata = df_avg_23_24)


## Best model!
exp_model3 <- nls(FC_night ~ a * exp(b * SWC_2_2_1), data = df_avg_23_24, start = list(a = 1, b = 0.1))

# Generate predicted values
df_avg_23_24$predicted3 <- predict(exp_model3, newdata = df_avg_23_24)


## Cut out winter
exp_model3_1 <- nls(FC_night ~ a * exp(b * SWC_2_2_1), data = df_nogs, start = list(a = 1, b = 0.1))

# Generate predicted values
df_avg_23_24$predicted3_1 <- predict(exp_model3_1, newdata = df_nogs)



#ch4
exp_model_ch4 <- nls(FCH4 ~ a * exp(b * SWC_1_1_1), data = df_avg_23_24, start = list(a = 1, b = 0.1))

# Generate predicted values
df_avg_23_24$predicted_ch4 <- predict(exp_model_ch4, newdata = df_avg_23_24)



```

## R Squared Values 

```{r}


# R squared values

r_squared <- function(model) {

  # Get residuals (only for data model actually used)
  resid <- residuals(model)

  # Get fitted values (only for data model actually used)
  fitted_vals <- fitted(model)

  # Back-calculate observed values (only for data model actually used)
  observed <- fitted_vals + resid

  # Now RSS and TSS are from the SAME dataset
  RSS <- sum(resid^2)
  TSS <- sum((observed - mean(observed))^2)

  R2 <- 1 - (RSS / TSS)

  return(R2)
}


rsq_1 <- r_squared(exp_model1)
rsq_2 <- r_squared(exp_model2)
rsq_3 <- r_squared(exp_model3)



#Full Year
rsq_co2 <- r_squared(exp_model1)
rsq_ch4 <- r_squared(exp_model_ch4)

# #No Spring
# rsq_co2_ns <- r_squared(exp_model_ns, df_nospring$FC_night)
# rsq_ch4_ns <- r_squared(exp_model_ch4_ns, df_nospring$FCH4)


```

### Plots


Plots flux variables vs. 5cm soil temp to visualize temperature/co2 flux relationship

Temp relationship plots with daily averages

```{r}
#Both Years CO2

co2model <- ggplot(data=df_avg_23_24)+
  theme_bw()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_point(aes(x=SWC_2_2_1, y=FC_night, col = DOY, shape = factor(season_year)))+
  geom_line(aes(x = SWC_2_2_1, y = predicted3))+
  scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression(""),
    y = expression("Half-hourly CO "[2] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("Nighttime CO"[2] * " Flux vs. SWC"))+
  scale_shape_manual(name = "Year", values = c(14, 15, 16, 17))+
  #scale_x_continuous(limits=c(-11,14))+
  scale_y_continuous(limits=c(-0.5,2.5))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_1, 2)),
           size = 5)

co2model




ch4model <- ggplot(data=df_avg_23_24)+
  theme_bw()+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_point(aes(x=SWC_1_1_1, y=FCH4*(1/1000), col = DOY, shape = factor(year)))+
  geom_line(aes(x = SWC_1_1_1, y = predicted_ch4*(1/1000)))+
  scale_color_gradient(low = "navy", high = "salmon")+
  labs(
    x = expression(""),
    y = expression("Half-hourly CO "[2] * " Flux ("*mu*mol~m^-2~s^-1*")"),
    title = expression("Nighttime CO"[2] * " Flux vs. SWC"))+
  scale_shape_manual(name = "Year", values = c(16, 17))+
  #scale_x_continuous(limits=c(-11,14))+
  scale_y_continuous(limits=c(-0.02,0.1))+
theme(axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), 
  axis.title = element_text(size = 14),legend.position = 'none')+
  annotate("text", 
           x = -Inf, y = Inf, 
           hjust = -0.1, vjust = 1.3,
           label = paste0("R² = ", round(rsq_1, 2)),
           size = 5)

ch4model

```


Code from Kelcy!
```{r}

# Extract statistics from exponential model 
exp_model <- nls(FC_night ~ a * exp(b * TS_3_1_1), data = fc_night_data, start = list(a = 1, b = 0.1)) 
# Get p-value for temperature effect (b parameter) 
p_value_temp <- summary(exp_model)$coefficients["b", "Pr(>|t|)"]

```

